/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './Components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'cascadia': ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'fira': ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'inter': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
        'poppins': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
        'jetbrains': ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'sf': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
        'code': ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'modern': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
        'elegant': ['Georgia', 'Times New Roman', 'serif'],
        'tech': ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'cursor': ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'system': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
      },
      colors: {
        vscode: {
          // Cursor Editor Dark Theme - Professional Glow & Perfect Contrast
          'editor-bg': '#0d1117',
          'sidebar-bg': '#161b22',
          'activitybar-bg': '#21262d',
          'titlebar-bg': '#21262d',
          'statusbar-bg': '#21262d',
          'statusbar-foreground': '#f0f6fc',
          'foreground': '#f0f6fc',
          'muted': '#8b949e',
          'accent': '#58a6ff',
          'accent-hover': '#79c0ff',
          'border': '#30363d',
          'border-hover': '#58a6ff',
          'selection': '#264f78',
          'selection-bg': '#21262d',
          'hover-background': '#262c36',
          'hover-glow': 'rgba(88, 166, 255, 0.1)',
          'card-bg': '#21262d',
          'card-hover': '#30363d',
          'tab-background': '#21262d',
          'tab-active-background': '#0d1117',
          'tab-active-foreground': '#f0f6fc',
          'tab-inactive-foreground': '#8b949e',
          'error': '#ff7b72',
          'warning': '#ffa657',
          'info': '#58a6ff',
          'success': '#3fb950',
          'keyword': '#ff7b72',
          'string': '#a5c9ea',
          'comment': '#8b949e',
          'variable': '#ffa657',
          'function': '#d2a8ff',
          'type': '#79c0ff',
          'number': '#79c0ff',
          'operator': '#ff7b72',
        },
        syntax: {
          'blue': '#58a6ff',
          'orange': '#ffa657',
          'green': '#3fb950',
          'cyan': '#79c0ff',
          'yellow': '#f9e2af',
          'red': '#ff7b72',
          'purple': '#d2a8ff',
          'pink': '#ff9bce',
        }
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'slide-in-left': 'slideInLeft 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.5s ease-out',
        'scale-in': 'scaleIn 0.4s ease-out',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-subtle': 'bounceSubtle 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'typing': 'typing 3.5s steps(40, end), blink-caret 0.75s step-end infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(0, 122, 204, 0.5)' },
          '100%': { boxShadow: '0 0 20px rgba(0, 122, 204, 0.8), 0 0 30px rgba(0, 122, 204, 0.6)' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        typing: {
          'from': { width: '0' },
          'to': { width: '100%' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'vscode': '0 0 0 1px rgba(60, 60, 60, 0.5)',
        'vscode-hover': '0 0 0 1px rgba(0, 122, 204, 0.5)',
        'glow': '0 0 20px rgba(0, 122, 204, 0.3)',
        'glow-strong': '0 0 30px rgba(0, 122, 204, 0.5)',
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
    },
  },
  plugins: [],
}
